sudo: false
language: node_js

before_install:
 - chmod +x ./scripts/*
 - ./scripts/before_install.sh

script: ./scripts/build.sh

after_success:
 - ./scripts/after_success.sh
after_failure:
- ./scripts/after_failure.sh

env:
  global:
    secure: "qK3j58jjgoWoumAnZWIcxQCwTYOLg94gsbqYauxpa3rpEJzeclc3Lf24TZJVlbo15FC6WF1S2aZKn6xylIqowKplNryhMqetSWy6MPIHFzgAc1phCVRzhW4axDCgPGeYxhwbdCWnRkKFA8MlT7We00OR+L8QfN5IexgYrrxCbxgfvy/hc3ffUEk6DOA9dpC7f+I8c2vitRPjw6QRwxdZ7ixPzYa7Bd/eym65DIy6ZskQXq9NP9XYjMs7X73xQ42hh4c4m0ceIvxQn/iwGtRK8X8pdQTs40h86VCqUkI/ggkdY1gJwnrUxgbZT28F0ylpwuN+jxBsZMdpDvqlZP0F7eNAae7t762Y72Ivlzjd9A7ZB6gBPw93c8dvX/2gD+VFVROJ7L6Y5VlNgkSaIK/F+7SgkQul/MxN058vAVpmYD/IbtLQQrj+hGzLMv5LYbRf+qWT4o8jxsmQp3Yh6gf/QCT43qIwgPI1LDNZ4ncB56iP+0EPRuqEbASP+ab7odGF2oELUXX9EXM/cEP0CpGnJhQTUVdp8BvTT61xSli+ek9gCwWDlzTHzyrvFy2chgT7sN4eJ8bA7K0jrD7pr0xrPNeQr+PCnSxucVFBs211P9fLjrGPJCAcpdrZVshFqkX/aTuEzB09lnb0nAPkwNUA5UZoz82wdeKIiKX1+rkZYzc="
